<?php declare(strict_types = 1);

$ignoreErrors = [];
$ignoreErrors[] = [
	'message' => '#^Property Doctrine\\\\ORM\\\\Mapping\\\\ClassMetadata\\<object\\>\\:\\:\\$table \\(array\\{name\\: string, schema\\?\\: string, indexes\\?\\: array, uniqueConstraints\\?\\: array, options\\?\\: array\\<string, mixed\\>, quoted\\?\\: bool\\}\\) does not accept array\\{\\}\\.$#',
	'identifier' => 'assign.propertyType',
	'count' => 1,
	'path' => __DIR__ . '/src/Bridge/Doctrine/MetadataLoadInterceptor.php',
];
$ignoreErrors[] = [
	'message' => '#^Trait Go\\\\Proxy\\\\Part\\\\PropertyInterceptionTrait is used zero times and is not analysed\\.$#',
	'identifier' => 'trait.unused',
	'count' => 1,
	'path' => __DIR__ . '/src/Proxy/Part/PropertyInterceptionTrait.php',
];
$ignoreErrors[] = [
	// ClassProxyGenerator is a code generator: the parent class name is valid but the class does not
	// exist yet at analysis time (it is defined in the weaved file after transformation).
	// class_exists() cannot be used here as the class is being generated, not loaded.
	'message' => '#^Parameter \#4 \$extends of class Laminas\\\\Code\\\\Generator\\\\ClassGenerator constructor expects class\-string\|null, string given\.$#',
	'identifier' => 'argument.type',
	'count' => 1,
	'path' => __DIR__ . '/src/Proxy/ClassProxyGenerator.php',
];
$ignoreErrors[] = [
	// Same reason as above: the introduced interface names are class names that will exist at runtime
	// but cannot be proven as class-string at static analysis time in a code generation context.
	'message' => '#^Parameter \#5 \$interfaces of class Laminas\\\\Code\\\\Generator\\\\ClassGenerator constructor expects array\<class\-string\>, array\<string\> given\.$#',
	'identifier' => 'argument.type',
	'count' => 1,
	'path' => __DIR__ . '/src/Proxy/ClassProxyGenerator.php',
];
$ignoreErrors[] = [
	// The __joinPoints property is generated by code generation at weave time and populated with
	// the proper array<array<array<Advice>>> structure. ReflectionProperty::getValue() returns mixed
	// because PHP reflection cannot know the type of dynamically generated properties.
	'message' => '#^Parameter \#1 \$classAdvices of static method Go\\\\Proxy\\\\ClassProxyGenerator::wrapWithJoinPoints\(\) expects array\<array\<array\<Go\\\\Aop\\\\Advice\>\>\>, mixed given\.$#',
	'identifier' => 'argument.type',
	'count' => 1,
	'path' => __DIR__ . '/src/Proxy/ClassProxyGenerator.php',
];

return ['parameters' => ['ignoreErrors' => $ignoreErrors]];
