<?php

declare(strict_types=1);

/**
 * Compiled advisor cache for the Go\Tests\TestProject\Aspect\DoSomethingAspect aspect.
 *
 * This file was generated by the Go! AOP framework, do not edit it manually.
 */

use Go\Aop\Framework\Interceptor;
use Go\Aop\Framework\The;
use Go\Aop\Framework\TraitIntroductionInfo;
use Go\Aop\Pointcut\AndPointcut;
use Go\Aop\Pointcut\AttributePointcut;
use Go\Aop\Pointcut\ClassInheritancePointcut;
use Go\Aop\Pointcut\MatchInheritedPointcut;
use Go\Aop\Pointcut\ModifierPointcut;
use Go\Aop\Pointcut\NamePointcut;
use Go\Aop\Pointcut\NotPointcut;
use Go\Aop\Pointcut\OrPointcut;
use Go\Aop\Pointcut\PointcutReference;
use Go\Aop\Pointcut\ReturnTypePointcut;
use Go\Aop\Pointcut\TruePointcut;
use Go\Aop\Support\GenericPointcutAdvisor;
use Go\Tests\TestProject\Annotation\Loggable;
use Go\Tests\TestProject\Application\BehaviorTrait;
use Go\Tests\TestProject\Application\FooInterface;
use Go\Tests\TestProject\Aspect\DoSomethingAspect;

return [
    'version' => 1,
    'advisors' => [
        DoSomethingAspect::class . '->afterDoSomething' => new GenericPointcutAdvisor(
            new OrPointcut(
                new AndPointcut(
                    1,
                    new NamePointcut(
                        127,
                        'Go\Tests\TestProject\Application\*',
                        true,
                    ),
                    new ModifierPointcut(
                        1,
                        notMask: 16,
                    ),
                    new NamePointcut(
                        1,
                        'doSomething',
                    ),
                ),
                new AndPointcut(
                    1,
                    new NotPointcut(new AttributePointcut(
                        1,
                        Loggable::class,
                    )),
                    new ReturnTypePointcut('string|int'),
                    new NamePointcut(
                        1,
                        'doSomethingElse',
                    ),
                    new ClassInheritancePointcut(FooInterface::class),
                    new MatchInheritedPointcut(),
                ),
            ),
            Interceptor::after(The::aspect(DoSomethingAspect::class)->afterDoSomething(...), order: 7, expression: 'execution(public Go\Tests\TestProject\Application\*->doSomething(*))'),
        ),
        DoSomethingAspect::class . '->introduction' => new GenericPointcutAdvisor(
            new AndPointcut(
                516,
                new NamePointcut(
                    127,
                    'Go\Tests\TestProject\Application\**',
                    true,
                ),
            ),
            new TraitIntroductionInfo(
                BehaviorTrait::class,
                FooInterface::class,
            ),
        ),
        DoSomethingAspect::class . '->methodPointcut' => new TruePointcut(1),
        DoSomethingAspect::class . '->referencedItem' => new PointcutReference('Go\Tests\TestProject\Aspect\DoSomethingAspect->methodPointcut'),
    ],
];
