<?php

declare(strict_types=1);
/*
 * Go! AOP framework
 *
 * @copyright Copyright 2026, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Go\Instrument\ZEngine;

use Go\Aop\Exception\InvalidConfigurationException;
use Go\Aop\Exception\WeavingException;
use Go\Core\AspectContainer;
use Go\Core\AspectKernel;
use Go\Instrument\ClassLoading\CachePathManager;
use Go\Instrument\PathResolver;
use Throwable;

/**
 * Index of the donor classes generated by the z-engine driver: `{cacheDir}/_zengine.cache`
 *
 * One record per loaded class name (what the loader has in hand), pointing at the generated
 * donor file and listing the advised methods - or recording that nothing matched the class, so
 * a warm request neither loads the aspects nor runs the matcher for it. Donor files live below
 * `{cacheDir}/_zengine/`, mirroring the application tree like the stream driver's proxies.
 *
 * The index is deliberately separate from the stream driver's transformation metadata: a record
 * without a cache URI is that driver's "serve natively, never weave" set in production, so
 * writing engine records into it would poison a cache directory later used by the stream driver.
 * Freshness is decided by the one shared rule, {@see CachePathManager::isFreshRecord()}.
 *
 * @phpstan-import-type KernelOptions from AspectKernel
 * @phpstan-type DonorRecord array{donor: string|null, donorClass: string|null, methods: list<string>}
 *
 * @internal Framework service, not a public extension point
 */
final class DonorCacheIndex
{
    /**
     * Version of the index format, an index of another version is ignored and rebuilt
     */
    public const int FORMAT_VERSION = 1;

    private const string INDEX_FILE_NAME = '/_zengine.cache';

    private const string DONOR_DIRECTORY = '/_zengine';

    private ?string $cacheDir;

    private string $appDir;

    /**
     * Records read from the index file, keyed by class name
     *
     * @var array<string, array<array-key, mixed>>
     */
    private array $records = [];

    private bool $recordsLoaded = false;

    /**
     * Records written during this request, keyed by class name
     *
     * @var array<string, array<string, mixed>>
     */
    private array $newRecords = [];

    /**
     * @phpstan-param KernelOptions $options
     */
    public function __construct(private readonly CachePathManager $cachePathManager, array $options)
    {
        $this->cacheDir = $options['cacheDir'];
        $this->appDir   = $options['appDir'];
    }

    /**
     * Returns the record of a class when it is still valid for its source file, null on a miss or a stale record
     *
     * @return DonorRecord|null
     */
    public function findFresh(string $className, string $resource, AspectContainer $container): ?array
    {
        $record = $this->newRecords[$className] ?? $this->records()[$className] ?? null;
        if ($record === null || !$this->cachePathManager->isFreshRecord($record, $resource, $container)) {
            return null;
        }
        $donor      = $record['donor'] ?? null;
        $donorClass = $record['donorClass'] ?? null;
        $methods    = is_array($record['methods'] ?? null) ? array_values(array_filter($record['methods'], is_string(...))) : [];
        if ($donor === null) {
            return ['donor' => null, 'donorClass' => null, 'methods' => []];
        }
        if (!is_string($donor) || !is_string($donorClass) || $donorClass === '' || !is_file($donor)) {
            // A record pointing at a missing donor file is rebuilt like a miss
            return null;
        }

        return ['donor' => $donor, 'donorClass' => $donorClass, 'methods' => $methods];
    }

    /**
     * Whether a source file lies below the application root: only those are woven (like with the stream driver,
     * whose cache mirrors the application tree), sources outside it are never touched
     */
    public function isApplicationSource(string $resource): bool
    {
        return PathResolver::isBelow($resource, $this->appDir);
    }

    /**
     * Returns the file the donor class of a source file is written to:
     * `{cacheDir}/_zengine/{path relative to appDir}/{Short}__AopDonor.php`
     *
     * @throws WeavingException For a source outside the application root, see {@see isApplicationSource()}
     */
    public function donorFileFor(string $resource, string $shortClassName): string
    {
        if ($this->cacheDir === null) {
            throw new InvalidConfigurationException('The donor index needs the `cacheDir` option to be configured');
        }
        $relativePath = PathResolver::rebase($resource, $this->appDir, '');
        if ($relativePath === null) {
            throw new WeavingException(sprintf('The source %s lies outside the application root %s and is never woven', $resource, $this->appDir));
        }
        $relativePath = ltrim($relativePath, '/\\');
        $directory    = str_replace('\\', '/', dirname($relativePath));

        return $this->cacheDir . self::DONOR_DIRECTORY . '/'
            . ($directory === '.' ? '' : $directory . '/')
            . $shortClassName . AspectContainer::DONOR_CLASS_SUFFIX . '.php';
    }

    /**
     * Records that no advisor matched the class
     */
    public function recordNoAdvices(string $className, string $resource): void
    {
        $this->newRecords[$className] = $this->baseRecord($resource) + [
            'donor'      => null,
            'donorClass' => null,
            'methods'    => [],
        ];
    }

    /**
     * Records the donor generated for the class
     *
     * @param list<string> $methods Advised method names
     */
    public function recordDonor(string $className, string $resource, string $donorFile, string $donorClass, array $methods): void
    {
        $this->newRecords[$className] = $this->baseRecord($resource) + [
            'donor'      => $donorFile,
            'donorClass' => $donorClass,
            'methods'    => $methods,
        ];
    }

    /**
     * Writes the records of this request into the index file (merged with the records already there)
     */
    public function flush(): void
    {
        if ($this->newRecords === [] || $this->cacheDir === null || !is_writable($this->cacheDir)) {
            return;
        }
        $allRecords = $this->newRecords + $this->records();
        $this->cachePathManager->writeIndexFile(self::INDEX_FILE_NAME, [
            'version' => self::FORMAT_VERSION,
            'classes' => $allRecords,
        ]);
        $this->records    = $allRecords;
        $this->newRecords = [];
    }

    /**
     * Safety net: records of a request are persisted at the latest when the index is released
     *
     * Losing a write is recoverable (the next request weaves again), an exception escaping a
     * destructor is not.
     */
    public function __destruct()
    {
        try {
            $this->flush();
        } catch (Throwable) {
            // Deliberately swallowed, see above
        }
    }

    /**
     * @return array<string, mixed>
     */
    private function baseRecord(string $resource): array
    {
        $fileTime = filemtime($resource);
        $fileSize = filesize($resource);

        return [
            'source'    => PathResolver::rebase($resource, $this->appDir, '') ?? $resource,
            'filemtime' => $fileTime !== false ? $fileTime : 0,
            'filesize'  => $fileSize !== false ? $fileSize : 0,
            'cachedAt'  => time(),
        ];
    }

    /**
     * Records of the index file, loaded once per request
     *
     * @return array<string, array<array-key, mixed>>
     */
    private function records(): array
    {
        if ($this->recordsLoaded) {
            return $this->records;
        }
        $this->recordsLoaded = true;
        $indexFile           = $this->cacheDir !== null ? $this->cacheDir . self::INDEX_FILE_NAME : null;
        if ($indexFile === null || !is_file($indexFile)) {
            return $this->records;
        }
        // Scope-isolated include: the file is a constant return array written atomically by the framework
        $indexData = (static fn(string $file): mixed => include $file)($indexFile);
        if (is_array($indexData) && ($indexData['version'] ?? null) === self::FORMAT_VERSION && is_array($indexData['classes'] ?? null)) {
            foreach ($indexData['classes'] as $className => $record) {
                if (is_string($className) && is_array($record)) {
                    $this->records[$className] = $record;
                }
            }
        }

        return $this->records;
    }
}
