<?php
/**
 * Go! OOP&AOP PHP framework
 *
 * @copyright     Copyright 2012, Lissachenko Alexander <lisachenko.it@gmail.com>
 * @license       http://www.opensource.org/licenses/mit-license.php The MIT License
 */

namespace Go\Aop;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-28 at 15:42:10.
 */
class TrueClassFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TrueClassFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = TrueClassFilter::getInstance();
    }

    /**
     * Test that true matcher always matches the class
     */
    public function testMatches()
    {
        // Works correctly with ReflectionClass
        $class = new \ReflectionClass('stdClass');
        $this->assertTrue($this->object->matches($class));
    }
}
