<?php

declare(strict_types=1);
/*
 * Go! AOP framework
 *
 * @copyright Copyright 2026, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Go\Stubs;

/**
 * Simulates the AOP proxy class generated by ClassProxyGenerator:
 * - Uses the original-body trait (TraitAliasProxied)
 * - Aliases each intercepted method as private <method>Original
 * - Overrides the public-facing methods with a sentinel (-1) so tests can
 *   confirm that the invocation goes through the alias, not the override.
 */
class TraitAliasProxy
{
    use TraitAliasProxied {
        TraitAliasProxied::publicMethod           as private publicMethodOriginal;
        TraitAliasProxied::getObjectId            as private getObjectIdOriginal;
        TraitAliasProxied::protectedMethod        as private protectedMethodOriginal;
        TraitAliasProxied::privateMethod          as private privateMethodOriginal;
        TraitAliasProxied::variadicArgsTest       as private variadicArgsTestOriginal;
        TraitAliasProxied::passByReference        as private passByReferenceOriginal;
        TraitAliasProxied::staticPassByReference  as private staticPassByReferenceOriginal;
        TraitAliasProxied::staticPublicMethod     as private staticPublicMethodOriginal;
        TraitAliasProxied::staticVariadicArgsTest as private staticVariadicArgsTestOriginal;
    }

    /**
     * Overridden by the proxy — returns a sentinel so tests can prove the invocation
     * routes through publicMethodOriginal (the trait alias) and not this override.
     */
    public function publicMethod(): int
    {
        return -1;
    }

    /** @see publicMethod */
    public static function staticPublicMethod(): string
    {
        return self::staticPublicMethodOriginal();
    }

    /**
     * Creates a first-class callable to the private getObjectIdOriginal alias.
     * Used by tests to verify that the static singleton joinpoint correctly rebinds
     * $this to each new caller instance via Closure::call().
     */
    public function createGetObjectIdCallable(): \Closure
    {
        return $this->getObjectIdOriginal(...);
    }

    /**
     * Creates a first-class callable to the private staticPublicMethodOriginal alias.
     * Used by tests to verify that the static singleton joinpoint correctly handles LSB
     * via forward_static_call().
     */
    public static function createStaticPublicMethodCallable(): \Closure
    {
        return self::staticPublicMethodOriginal(...);
    }

    /**
     * Returns a first-class callable to the private Original-suffixed alias for the given instance method.
     * Used by unit tests to provide the required callable argument to invocation constructors.
     */
    public function getCallableFor(string $method): \Closure
    {
        return match ($method) {
            'publicMethod'      => $this->publicMethodOriginal(...),
            'getObjectId'       => $this->getObjectIdOriginal(...),
            'protectedMethod'   => $this->protectedMethodOriginal(...),
            'privateMethod'     => $this->privateMethodOriginal(...),
            'variadicArgsTest'  => $this->variadicArgsTestOriginal(...),
            'passByReference'   => $this->passByReferenceOriginal(...),
            default             => throw new \InvalidArgumentException("No Original-suffixed alias for '$method'"),
        };
    }

    /**
     * Returns a first-class callable to the private Original-suffixed alias for the given static method.
     * Used by unit tests to provide the required callable argument to invocation constructors.
     */
    public static function getStaticCallableFor(string $method): \Closure
    {
        return match ($method) {
            'staticPassByReference'  => self::staticPassByReferenceOriginal(...),
            'staticPublicMethod'     => self::staticPublicMethodOriginal(...),
            'staticVariadicArgsTest' => self::staticVariadicArgsTestOriginal(...),
            default                  => throw new \InvalidArgumentException("No static Original-suffixed alias for '$method'"),
        };
    }
}
