<?php

declare(strict_types=1);
/*
 * Go! AOP framework
 *
 * @copyright Copyright 2026, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Go\Stubs;

/**
 * Simulates the AOP proxy class generated by ClassProxyGenerator:
 * - Uses the original-body trait (TraitAliasProxied)
 * - Aliases each intercepted method as private __aop__<method>
 * - Overrides the public-facing methods with a sentinel (-1) so tests can
 *   confirm that the invocation goes through the alias, not the override.
 */
class TraitAliasProxy
{
    use TraitAliasProxied {
        TraitAliasProxied::publicMethod           as private __aop__publicMethod;
        TraitAliasProxied::protectedMethod        as private __aop__protectedMethod;
        TraitAliasProxied::privateMethod          as private __aop__privateMethod;
        TraitAliasProxied::variadicArgsTest       as private __aop__variadicArgsTest;
        TraitAliasProxied::passByReference        as private __aop__passByReference;
        TraitAliasProxied::staticPublicMethod     as private __aop__staticPublicMethod;
        TraitAliasProxied::staticVariadicArgsTest as private __aop__staticVariadicArgsTest;
    }

    /**
     * Overridden by the proxy — returns a sentinel so tests can prove the invocation
     * routes through __aop__publicMethod (the trait alias) and not this override.
     */
    public function publicMethod(): int
    {
        return -1;
    }

    /** @see publicMethod */
    public static function staticPublicMethod(): int
    {
        return -1;
    }
}
