<?php

declare(strict_types=1);
/*
 * Go! AOP framework
 *
 * @copyright Copyright 2026, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Go\Core;

use Go\Aop\Advisor;
use Go\Aop\CompilableToPhp;
use Go\Aop\Pointcut;
use PhpParser\Node;
use PhpParser\Node\Arg;
use PhpParser\Node\ArrayItem;
use PhpParser\Node\Expr;
use PhpParser\Node\Expr\Array_;
use PhpParser\Node\Expr\BinaryOp\Concat;
use PhpParser\Node\Expr\ClassConstFetch;
use PhpParser\Node\Expr\New_;
use PhpParser\Node\Expr\StaticCall;
use PhpParser\Node\Identifier;
use PhpParser\Node\Name;
use PhpParser\Node\Name\FullyQualified;
use PhpParser\Node\Scalar\Int_;
use PhpParser\Node\Scalar\String_;

/**
 * Compiles loaded aspect advisors into an includable plain-PHP cache file.
 *
 * The produced file returns a versioned payload where the whole pointcut/advisor
 * graph is expressed as nested static constructor expressions, so loading the cache
 * is a single opcache-friendly include with no unserialization involved.
 *
 * @internal
 */
final class AdvisorCacheCompiler
{
    /**
     * Version of the compiled advisor cache format
     */
    public const int VERSION = 1;

    /**
     * Compiles the loaded items of one aspect into advisor cache file content
     *
     * @param class-string                      $aspectClassName Aspect the items were loaded from
     * @param array<array-key, Pointcut|Advisor> $items          Loaded pointcuts and advisors, keyed by advisor id
     *                                                           (an integer-like string id surfaces as an int key)
     *
     * @throws NotCompilableException When any item cannot be expressed as plain PHP
     */
    public function compile(string $aspectClassName, array $items): string
    {
        $advisorItems = [];
        foreach ($items as $itemId => $item) {
            if (!$item instanceof CompilableToPhp) {
                throw new NotCompilableException(
                    'Cannot compile an instance of ' . get_debug_type($item) . ' into plain PHP',
                );
            }
            $advisorItems[] = new ArrayItem($item->compileToPhp(), self::compileAdvisorKey($itemId));
        }

        $payload = new Array_(
            [
                new ArrayItem(new Int_(self::VERSION), new String_('version')),
                new ArrayItem(
                    new Array_($advisorItems, ['kind' => Array_::KIND_SHORT]),
                    new String_('advisors'),
                ),
            ],
            ['kind' => Array_::KIND_SHORT],
        );

        $useStatements = $this->shortenClassNames($payload);

        $printedUses    = $useStatements === [] ? '' : implode("\n", $useStatements) . "\n\n";
        $printedPayload = new AdvisorCachePrinter(['shortArraySyntax' => true])->prettyPrintExpr($payload);

        return "<?php\n\ndeclare(strict_types=1);\n\n"
            . "/**\n"
            . " * Compiled advisor cache for the {$aspectClassName} aspect.\n"
            . " *\n"
            . " * This file was generated by the Go! AOP framework, do not edit it manually.\n"
            . " */\n\n"
            . $printedUses
            . 'return ' . $printedPayload . ";\n";
    }

    /**
     * Compiles an ordered parameter list into call arguments
     *
     * Trailing arguments holding their declared defaults are omitted entirely; when an
     * earlier default is skipped, the remaining arguments are emitted as named arguments.
     *
     * @internal Helper for {@see CompilableToPhp} implementations
     *
     * @param list<array{string, Expr, bool}> $parameters Parameter name, value expression
     *                                                    and whether the value equals the declared default
     *
     * @return list<Arg>
     */
    public static function compileArgs(array $parameters): array
    {
        while ($parameters !== [] && $parameters[count($parameters) - 1][2]) {
            array_pop($parameters);
        }

        $args           = [];
        $skippedDefault = false;
        foreach ($parameters as [$parameterName, $valueExpression, $isDefault]) {
            if ($isDefault) {
                $skippedDefault = true;
                continue;
            }
            $args[] = new Arg($valueExpression, name: $skippedDefault ? new Identifier($parameterName) : null);
        }

        return $args;
    }

    /**
     * Compiles an advisor id into its array key expression
     *
     * Ids of the "Aspect\ClassName->member" form are emitted as a `ClassName::class . '->member'`
     * concatenation, producing exactly the same runtime string as the direct aspect loader.
     * The class part is checked purely syntactically - deciding by existence is not an option,
     * as compilation may run in the middle of a class load inside the autoloader.
     */
    private static function compileAdvisorKey(int|string $itemId): Expr
    {
        if (is_int($itemId)) {
            return new Int_($itemId);
        }

        $separatorPosition = strpos($itemId, '->');
        if ($separatorPosition !== false) {
            $className = substr($itemId, 0, $separatorPosition);
            if (preg_match('/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*(\\\\[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*)*$/', $className) === 1) {
                return new Concat(
                    new ClassConstFetch(new FullyQualified($className), 'class'),
                    new String_(substr($itemId, $separatorPosition)),
                );
            }
        }

        return new String_($itemId);
    }

    /**
     * Replaces fully-qualified class references with short names backed by a sorted "use" block
     *
     * Short names that would collide between different namespaces stay fully qualified inline.
     *
     * @return list<string> Printable "use Fqcn;" statements, sorted by class name
     */
    private function shortenClassNames(Array_ $payload): array
    {
        /** @var array<string, array<string, true>> $namesByShortName Short name => set of fully-qualified names */
        $namesByShortName = [];
        self::walkClassReferences($payload, function (New_|StaticCall|ClassConstFetch $node) use (&$namesByShortName): void {
            $className = $node->class;
            if ($className instanceof FullyQualified) {
                $namesByShortName[$className->getLast()][$className->toString()] = true;
            }
        });

        /** @var array<string, string> $aliasMap Fully-qualified name => short alias */
        $aliasMap = [];
        foreach ($namesByShortName as $shortName => $fullNames) {
            // Conflicting short names stay fully qualified inline
            if (count($fullNames) === 1) {
                $aliasMap[array_key_first($fullNames)] = $shortName;
            }
        }

        self::walkClassReferences($payload, function (New_|StaticCall|ClassConstFetch $node) use ($aliasMap): void {
            $className = $node->class;
            if ($className instanceof FullyQualified && isset($aliasMap[$className->toString()])) {
                $node->class = new Name($aliasMap[$className->toString()]);
            }
        });

        $fullNames = array_keys($aliasMap);
        sort($fullNames, SORT_STRING);

        return array_map(static fn(string $fullName): string => "use {$fullName};", $fullNames);
    }

    /**
     * Recursively visits every class-referencing expression inside the node
     *
     * @param callable(New_|StaticCall|ClassConstFetch): void $callback
     */
    private static function walkClassReferences(Node $node, callable $callback): void
    {
        if ($node instanceof New_ || $node instanceof StaticCall || $node instanceof ClassConstFetch) {
            $callback($node);
        }
        foreach ($node->getSubNodeNames() as $subNodeName) {
            $subNode = $node->$subNodeName;
            foreach (is_array($subNode) ? $subNode : [$subNode] as $childNode) {
                if ($childNode instanceof Node) {
                    self::walkClassReferences($childNode, $callback);
                }
            }
        }
    }
}
