<?php
declare(strict_types = 1);
/*
 * Go! AOP framework
 *
 * @copyright Copyright 2012, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Go\Aop\Support;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-28 at 15:42:10.
 */
class TruePointFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TruePointFilter
     */
    protected $filter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->filter = TruePointFilter::getInstance();
    }

    /**
     * Test that true matcher always matches the class
     */
    public function testMatches()
    {
        // Works correctly with ReflectionClass
        $class = new \ReflectionClass('stdClass');
        $this->assertTrue($this->filter->matches($class));
    }
}
