name: "Coding standards"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  php-cs-fixer:
    name: "php-cs-fixer (PER-CS)"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
      - name: "Cache dependencies"
        uses: actions/cache@v6
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "composer-${{ runner.os }}-php-8.4-highest-${{ hashFiles('composer.json') }}"
          restore-keys: "composer-${{ runner.os }}-php-8.4-highest-"
      - name: "Validate composer.json"
        run: "composer validate --strict --no-check-lock"
      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"
      - name: "Check coding standards"
        run: "vendor/bin/php-cs-fixer check --diff --format=checkstyle | cs2pr"
