name: "PHPStan analysis"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2
      - name: "Cache dependencies"
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"
      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"
      - name: "Static analysis"
        uses: chindit/actions-phpstan@master
